config/routes.rb
Coda::Application.routes.draw do

  match '/documents/:type'                => 'documents#index',     :as => :typed_documents, :constraints => {:type => /\D+/}
  match '/info/:slug'                     => 'pages#show',          :as => :view_page
  match '/intergroup'                     => 'pages#intergroup',    :as => :intergroup
  match '/contact'                        => 'messages#new',        :as => :contact
  
  match '/messages'                       => 'messages#new',              :via => :get
  match '/messages/voicemail'             => 'messages#create_voicemail', :via => :post

  match '/meetings/address/:address_id'   => 'meetings#index',      :as => :meetings_by_address
  match '/meetings/:district'             => 'meetings#index',      :as => :meetings_by_district, :constraints => {:district => /\D+/}
  
  match '/forums/:id/posts/new'           => 'forum_posts#new',     :as => :new_post_in_forum, :constraints => {:id => /\d+/}
  match '/forum_posts/:id/replies/new'    => 'forum_replies#new',   :as => :new_reply_to_post, :constraints => {:id => /\d+/}
  
  match 'announcements_ticker'            => 'announcements#index', :as => :announcements_ticker, :defaults => {:limit => 5, :format => 'json'}
  
  
  resources :announcements, :only => [:show, :index], :default => {:format => 'html'}
  resources :documents, :only => [:show, :index]
  resources :motions, :only => [:show, :index]
  resources :intergroup_sessions, :only => [:show, :index]
  resources :meetings, :only => [:show, :index]
  resources :transactions
  resources :messages, :only => [:new, :create, :show]
  resources :forums, :only => [:index, :show]
  resources :forum_posts
  resources :forum_replies, :only => [:create]

  match '/admin'                                  => 'admin/admin#admin',                  :as => :admin                                 
  match '/admin/documents/add_transaction'        => 'admin/documents#add_transaction',    :as => :add_admin_document_transaction
  match '/admin/documents/update_transaction/:id' => 'admin/documents#update_transaction', :as => :update_admin_document_transaction
  match '/admin/messages/:id/status/:status'      => 'admin/messages#status',              :as => :update_admin_message_status
  match '/admin/messages/all'                     => 'admin/messages#index',               :as => :admin_all_messages, :defaults => { :show_all => 'true' }
  
  namespace :admin do
    resources :announcements
    resources :contents
    resources :pages
    resources :documents
    resources :motions
    resources :intergroup_sessions
    resources :districts
    resources :meetings
    resources :meeting_addresses
    resources :menus
    resources :messages
    resources :transactions
    resources :site_configs
    resources :forums
  end
  

  match '/twilio/start'                                                  => 'twilio#start', :defaults => { :format => 'xml' }
  match '/twilio/district_list'                                          => 'twilio#district_list', :defaults => { :format => 'xml' }
  match '/twilio/meeting_list/:district_id'                              => 'twilio#meeting_list', :defaults => { :format => 'xml' }
  match '/twilio/meeting_list/:district_id/meeting_detail/:meeting_id'   => 'twilio#meeting_detail', :defaults => { :format => 'xml' }
  match '/twilio/info/:key'                                              => 'twilio#info', :defaults => { :format => 'xml' }
  match '/twilio/voicemail'                                              => 'twilio#voicemail', :defaults => { :format => 'xml' }
  

  root :to => 'pages#home'

end

app/views/admin/pages/_form.html.erb
<%= form_for([:admin, @page]) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug, "Path" %>
    <%= f.text_field :slug %> <span class="note">(the 'path' is what will show up in the URL)</span>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, :id => "wysiwyg" %>
  </div>
  <div class="field">
    <%= f.label :published, :class => "alt_label" %>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= render :partial => "/admin/wysiwyg" %>

<script type="text/javascript" charset="utf-8">
  $("#page_name").on("keyup", function(){
    $("#page_slug").val(URLify($(this).val()), 64);
  });
  $("#page_slug").focus(function(){
    $("#page_name").off("keyup");
  });
</script>

app/views/admin/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', view_page_path(@page.slug) %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Path</th>
    <th>Published</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= page.slug %></td>
    <td><%= page.published %></td>
    <td><%= link_to 'Show', admin_page_path(page) %></td>
    <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
    <td><%= link_to 'Remove', admin_page_path(page), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @page.name %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>

<p>
  <b>Published:</b>
  <%= @page.published %>
</p>


<%= link_to 'Edit', edit_admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>