config/routes.rb
Coda::Application.routes.draw do

  match '/documents/:type'                => 'documents#index',     :as => :typed_documents, :constraints => {:type => /\D+/}
  match '/info/:slug'                     => 'pages#show',          :as => :view_page
  match '/intergroup'                     => 'pages#intergroup',    :as => :intergroup
  match '/contact'                        => 'messages#new',        :as => :contact
  
  match '/messages'                       => 'messages#new',              :via => :get
  match '/messages/voicemail'             => 'messages#create_voicemail', :via => :post

  match '/meetings/address/:address_id'   => 'meetings#index',      :as => :meetings_by_address
  match '/meetings/:district'             => 'meetings#index',      :as => :meetings_by_district, :constraints => {:district => /\D+/}
  
  match '/forums/:id/posts/new'           => 'forum_posts#new',     :as => :new_post_in_forum, :constraints => {:id => /\d+/}
  match '/forum_posts/:id/replies/new'    => 'forum_replies#new',   :as => :new_reply_to_post, :constraints => {:id => /\d+/}
  
  match 'announcements_ticker'            => 'announcements#index', :as => :announcements_ticker, :defaults => {:limit => 5, :format => 'json'}
  
  
  resources :announcements, :only => [:show, :index], :default => {:format => 'html'}
  resources :documents, :only => [:show, :index]
  resources :motions, :only => [:show, :index]
  resources :intergroup_sessions, :only => [:show, :index]
  resources :meetings, :only => [:show, :index]
  resources :transactions
  resources :messages, :only => [:new, :create, :show]
  resources :forums, :only => [:index, :show]
  resources :forum_posts
  resources :forum_replies, :only => [:create]

  match '/admin'                                  => 'admin/admin#admin',                  :as => :admin                                 
  match '/admin/documents/add_transaction'        => 'admin/documents#add_transaction',    :as => :add_admin_document_transaction
  match '/admin/documents/update_transaction/:id' => 'admin/documents#update_transaction', :as => :update_admin_document_transaction
  match '/admin/messages/:id/status/:status'      => 'admin/messages#status',              :as => :update_admin_message_status
  match '/admin/messages/all'                     => 'admin/messages#index',               :as => :admin_all_messages, :defaults => { :show_all => 'true' }
  
  namespace :admin do
    resources :announcements
    resources :contents
    resources :pages
    resources :documents
    resources :motions
    resources :intergroup_sessions
    resources :districts
    resources :meetings
    resources :meeting_addresses
    resources :menus
    resources :messages
    resources :transactions
    resources :site_configs
    resources :forums
  end
  

  match '/twilio/start'                                                  => 'twilio#start', :defaults => { :format => 'xml' }
  match '/twilio/district_list'                                          => 'twilio#district_list', :defaults => { :format => 'xml' }
  match '/twilio/meeting_list/:district_id'                              => 'twilio#meeting_list', :defaults => { :format => 'xml' }
  match '/twilio/meeting_list/:district_id/meeting_detail/:meeting_id'   => 'twilio#meeting_detail', :defaults => { :format => 'xml' }
  match '/twilio/info/:key'                                              => 'twilio#info', :defaults => { :format => 'xml' }
  match '/twilio/voicemail'                                              => 'twilio#voicemail', :defaults => { :format => 'xml' }
  

  root :to => 'pages#home'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :meeting_address
  accepts_nested_attributes_for :meeting_address
  
  def day
    Date::DAYNAMES[wday] + "s"
  end
  
  def time
    Time.new(2000, 1, 1, hour, minute).strftime("%l:%M%p")
  end
  
  def next_meeting_date
    today = Date.today
    cwday = wday == 0 ? 7 : wday
    next_cweek = (today.cweek == 52 ? 0 : today.cweek) + 1 
    today.cwday > cwday ? DateTime.commercial((today + 7).year, next_cweek, cwday, hour, minute) : DateTime.commercial(today.year, today.cweek, cwday, hour, minute)
  end
  
  def self.upcoming(limit = 3)
    Meeting.all.sort { |a,b| a.next_meeting_date <=> b.next_meeting_date }[0..(limit - 1)]
  end
end

app/controllers/admin/meetings_controller.rb
class Admin::MeetingsController < ApplicationController
  http_basic_authenticate_with :name => SITE_CONFIG['username'], :password => SITE_CONFIG['password'] if SITE_CONFIG['perform_authentication']
  layout 'admin'

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    redirect_to(new_admin_district_path, notice: 'Please create a District before adding a new Meeting') and return if District.all.empty?
    
    @meeting = Meeting.new
    @meeting.meeting_address = MeetingAddress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])
    
    unless @meeting.meeting_address_id.to_i > 0
      @meeting.meeting_address = MeetingAddress.new(params[:meeting_address])
      @meeting.meeting_address.save
    end
      
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to admin_meeting_path(@meeting), notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to admin_meeting_path(@meeting), notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to admin_meetings_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @address_id = params[:address_id].to_i
    
    if @address_id > 0
      @meeting_addresses = [MeetingAddress.find(params[:address_id])]
      @districts = [@meeting_addresses.first.district]
    else
      @districts = params[:district].blank? ? District.all : [District.find_by_slug(params[:district])]
      @meeting_addresses = MeetingAddress.where("district_id in (?)", @districts.collect{|d| d.id})
    end
    
    @map_addresses = @meeting_addresses.collect{|ma| ["'#{ma.building} (meetings: #{ma.meetings.count})'", ma.lat, ma.lng, (ma.meetings.size > 1 ? meetings_by_address_url(ma.id) : meeting_url(ma.meetings.first.id))]}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: Meeting.all }
      format.pdf do
        render :pdf => "index",
               :layout => "pdf.html",
               :no_background => false,
               :show_as_html => params[:debug].present?,
               :page_size => "A3",
               :margin => {
                 :top                => 0,
                 :bottom             => 0,
                 :left               => 0,
                 :right              => 0
               }
      end
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end
end

app/views/meetings/index.html.erb
<h1>Meeting List</h1>

<%= render_content('meetings_intro') %>

<% @districts.each do |district| %>
<table class="meeting_list" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th class="district"><h3><%= link_to district.name, meetings_by_district_path(:district => district.slug) %></h3></th>
      <% Date::DAYNAMES.each do |day| %>
        <th><%= day[0..2].upcase %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% district.meeting_addresses.delete_if{|d| (@address_id > 0) and (d.id != @address_id)}.each do |meeting_address| %>
    <tr>
      <td class="building"><%= meeting_address.building %><br><div class="note"><%= meeting_address.street1 %></div></td>
      <% 7.times do |wday| %>
        <td class="time">
          <% meeting_address.meetings.each do |meeting| %>
            <% if wday == meeting.wday %>
              <%= link_to meeting.time, meeting_path(meeting) %>
            <% end %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<div id="google_map" class="meeting_list_map" style="width: 100%; height: 500px;"></div>
<script type="text/javascript" charset="utf-8">
var _map_addresses = <%= raw @map_addresses.to_json -%>;

function showMeetingsMap() {
  var locations = _map_addresses;
  var latlng = new google.maps.LatLng(0, 0);
  var bounds = new google.maps.LatLngBounds();
  var myOptions = {
      panControl: false,
      streetViewControl: false,
      mapTypeControlOptions: { style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
      mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("google_map"), myOptions);
  var marker, markerLatLng, i;
  for (i = 0; i < locations.length; i++) {
    markerLatLng = new google.maps.LatLng(locations[i][1], locations[i][2]);
    marker = new google.maps.Marker({
      map: map,
      position: markerLatLng,
      title: locations[i][0].replace(/'|"/gi,"")
    });
    google.maps.event.addListener(marker, 'click', (function(marker, i) {
      return function() {
        // infowindow.setContent(locations[i][0]);
        // infowindow.open(map, marker);
        window.location.href = locations[i][3];
      }
    })(marker, i));
    bounds.extend(markerLatLng);
    map.fitBounds(bounds);
  }
}

loadGoogleMap(0, 0, 'showMeetingsMap');
</script>

app/views/meetings/index.pdf.erb
<h1><%= SiteConfig.get('organization_name') %> Meeting List</h1>

<table class="header">
  <tr>
    <td class="logo"><%= wicked_pdf_image_tag 'pdf_logo.png' %></td>
    <td><%= render_content('meetings_pdf_intro') %></td>
  </tr>
</table>

<% @districts.each do |district| %>
<table class="meeting_list" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th class="district"><h3><%= district.name %></h3></th>
      <% Date::DAYNAMES.each do |day| %>
        <th><%= day[0..2].upcase %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% district.meeting_addresses.delete_if{|d| (@address_id > 0) and (d.id != @address_id)}.each do |meeting_address| %>
    <tr class="<%= cycle("", "even") %>">
      <td class="building">
        <%= meeting_address.building %><br>
        <span class="note">
          <%= meeting_address.street1 %>
          <%= ", " + meeting_address.street2 unless meeting_address.street2.blank? %><br />
          <%= meeting_address.city %><%= ", " + meeting_address.state.upcase unless meeting_address.state.blank? %>
          <%= meeting_address.zip_code %>
        </span>
      </td>
      <% 7.times do |wday| %>
        <td class="time">
          <% meeting_address.meetings.each do |meeting| %>
            <% if wday == meeting.wday %>
              <%= link_to meeting.time, meeting_url(meeting) %>
            <% end %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  <% reset_cycle %>
  </tbody>
</table>
<% end %>


<div class="footer"><%= render_content('meetings_pdf_footer') %></div>

app/views/meetings/show.html.erb
<h1>Meeting Detail</h1>

<h2><%= @meeting.title %></h2>
<dl>
  <dt>Day of Week:</dt><dd><%= @meeting.day %></dd>
  <dt>Time of Day:</dt><dd><%= @meeting.time %></dd>
  <dt>Location:</dt>
  <dd class="clearfix">
    <address>
      <%= @meeting.meeting_address.building %><br>
      <%= @meeting.meeting_address.street1 %>
      <%= @meeting.meeting_address.street2 %><br>
      <%= @meeting.meeting_address.city %>, <%= @meeting.meeting_address.state %> <%= @meeting.meeting_address.zip_code %><br>
      <span class="note"><%= @meeting.meeting_address.notes %></span>
    </address>
  </dd>
  <% unless @meeting.topic.blank? %><dt>Meeting Focus:</dt><dd><%= @meeting.topic %></dd><% end %>
</dl>

<div id="google_map"></div>

<script type="text/javascript" charset="utf-8">
  loadGoogleMap(<%= @meeting.meeting_address.lat %>, <%= @meeting.meeting_address.lng %>);
</script>