config/routes.rb
Coda::Application.routes.draw do

  match '/documents/:type'                => 'documents#index',     :as => :typed_documents, :constraints => {:type => /\D+/}
  match '/info/:slug'                     => 'pages#show',          :as => :view_page
  match '/intergroup'                     => 'pages#intergroup',    :as => :intergroup
  match '/contact'                        => 'messages#new',        :as => :contact
  
  match '/messages'                       => 'messages#new',              :via => :get
  match '/messages/voicemail'             => 'messages#create_voicemail', :via => :post

  match '/meetings/address/:address_id'   => 'meetings#index',      :as => :meetings_by_address
  match '/meetings/:district'             => 'meetings#index',      :as => :meetings_by_district, :constraints => {:district => /\D+/}
  
  match '/forums/:id/posts/new'           => 'forum_posts#new',     :as => :new_post_in_forum, :constraints => {:id => /\d+/}
  match '/forum_posts/:id/replies/new'    => 'forum_replies#new',   :as => :new_reply_to_post, :constraints => {:id => /\d+/}
  
  match 'announcements_ticker'            => 'announcements#index', :as => :announcements_ticker, :defaults => {:limit => 5, :format => 'json'}
  
  
  resources :announcements, :only => [:show, :index], :default => {:format => 'html'}
  resources :documents, :only => [:show, :index]
  resources :motions, :only => [:show, :index]
  resources :intergroup_sessions, :only => [:show, :index]
  resources :meetings, :only => [:show, :index]
  resources :transactions
  resources :messages, :only => [:new, :create, :show]
  resources :forums, :only => [:index, :show]
  resources :forum_posts
  resources :forum_replies, :only => [:create]

  match '/admin'                                  => 'admin/admin#admin',                  :as => :admin                                 
  match '/admin/documents/add_transaction'        => 'admin/documents#add_transaction',    :as => :add_admin_document_transaction
  match '/admin/documents/update_transaction/:id' => 'admin/documents#update_transaction', :as => :update_admin_document_transaction
  match '/admin/messages/:id/status/:status'      => 'admin/messages#status',              :as => :update_admin_message_status
  match '/admin/messages/all'                     => 'admin/messages#index',               :as => :admin_all_messages, :defaults => { :show_all => 'true' }
  
  namespace :admin do
    resources :announcements
    resources :contents
    resources :pages
    resources :documents
    resources :motions
    resources :intergroup_sessions
    resources :districts
    resources :meetings
    resources :meeting_addresses
    resources :menus
    resources :messages
    resources :transactions
    resources :site_configs
    resources :forums
  end
  

  match '/twilio/start'                                                  => 'twilio#start', :defaults => { :format => 'xml' }
  match '/twilio/district_list'                                          => 'twilio#district_list', :defaults => { :format => 'xml' }
  match '/twilio/meeting_list/:district_id'                              => 'twilio#meeting_list', :defaults => { :format => 'xml' }
  match '/twilio/meeting_list/:district_id/meeting_detail/:meeting_id'   => 'twilio#meeting_detail', :defaults => { :format => 'xml' }
  match '/twilio/info/:key'                                              => 'twilio#info', :defaults => { :format => 'xml' }
  match '/twilio/voicemail'                                              => 'twilio#voicemail', :defaults => { :format => 'xml' }
  

  root :to => 'pages#home'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :meeting_address
  accepts_nested_attributes_for :meeting_address
  
  def day
    Date::DAYNAMES[wday] + "s"
  end
  
  def time
    Time.new(2000, 1, 1, hour, minute).strftime("%l:%M%p")
  end
  
  def next_meeting_date
    today = Date.today
    cwday = wday == 0 ? 7 : wday
    next_cweek = (today.cweek == 52 ? 0 : today.cweek) + 1 
    today.cwday > cwday ? DateTime.commercial((today + 7).year, next_cweek, cwday, hour, minute) : DateTime.commercial(today.year, today.cweek, cwday, hour, minute)
  end
  
  def self.upcoming(limit = 3)
    Meeting.all.sort { |a,b| a.next_meeting_date <=> b.next_meeting_date }[0..(limit - 1)]
  end
end

app/controllers/admin/meetings_controller.rb
class Admin::MeetingsController < ApplicationController
  http_basic_authenticate_with :name => SITE_CONFIG['username'], :password => SITE_CONFIG['password'] if SITE_CONFIG['perform_authentication']
  layout 'admin'

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    redirect_to(new_admin_district_path, notice: 'Please create a District before adding a new Meeting') and return if District.all.empty?
    
    @meeting = Meeting.new
    @meeting.meeting_address = MeetingAddress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])
    
    unless @meeting.meeting_address_id.to_i > 0
      @meeting.meeting_address = MeetingAddress.new(params[:meeting_address])
      @meeting.meeting_address.save
    end
      
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to admin_meeting_path(@meeting), notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to admin_meeting_path(@meeting), notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to admin_meetings_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @address_id = params[:address_id].to_i
    
    if @address_id > 0
      @meeting_addresses = [MeetingAddress.find(params[:address_id])]
      @districts = [@meeting_addresses.first.district]
    else
      @districts = params[:district].blank? ? District.all : [District.find_by_slug(params[:district])]
      @meeting_addresses = MeetingAddress.where("district_id in (?)", @districts.collect{|d| d.id})
    end
    
    @map_addresses = @meeting_addresses.collect{|ma| ["'#{ma.building} (meetings: #{ma.meetings.count})'", ma.lat, ma.lng, (ma.meetings.size > 1 ? meetings_by_address_url(ma.id) : meeting_url(ma.meetings.first.id))]}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: Meeting.all }
      format.pdf do
        render :pdf => "index",
               :layout => "pdf.html",
               :no_background => false,
               :show_as_html => params[:debug].present?,
               :page_size => "A3",
               :margin => {
                 :top                => 0,
                 :bottom             => 0,
                 :left               => 0,
                 :right              => 0
               }
      end
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end
end

app/views/admin/meetings/edit.html.erb
<h1>Edit meeting</h1>

<%= form_for([:admin,@meeting]) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h1><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h1>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <fieldset class="existing_address">
    <%= f.select :meeting_address_id, option_groups_from_collection_for_select(District.all, :meeting_addresses, :name, :id, :short_address, @meeting.meeting_address.id), :include_blank => true %>
    <p id="link_new_address">or <%= link_to "create a new address", new_admin_meeting_address_path %></p>
  </fieldset>
  
  <fieldset class="new_address" style="display: none">
  <%= fields_for @meeting.meeting_address do |af| %>
    <%= af.hidden_field :lat, :id => 'google_maps_address_lat' %>
    <%= af.hidden_field :lng, :id => 'google_maps_address_lng' %>
  
    <div class="field">
      <%= af.label :district_id %><br />
      <%= af.select :district_id, District.all.collect{|d| [d.name, d.id]}.sort %>
    </div>

    <div class="field">
      <%= af.label :building %><br />
      <%= af.text_field :building %>
    </div>
    <div class="field">
      <%= af.label :street1 %><br />
      <%= af.text_field :street1 %>
    </div>
    <div class="field">
      <%= af.label :street2 %><br />
      <%= af.text_field :street2 %>
    </div>
    <div class="field">
      <%= af.label :city %><br />
      <%= af.text_field :city %>
    </div>
    <div class="field">
      <%= af.label :state %><br />
      <%= af.text_field :state, :class => "uppercase" %>
    </div>
    <div class="field">
      <%= af.label :zip_code %><br />
      <%= af.text_field :zip_code %>
    </div>
    <div class="field">
      <%= af.label :notes %><br />
      <%= af.text_field :notes %>
    </div>
  <% end %>
  </fieldset>
  
  <div id="google_map">
  </div>
  
  <div class="field">
    <%= f.label :wday, 'Day' %><br />
    <%= f.select :wday, Date::DAYNAMES.zip((0..6).to_a) %>
  </div>
  <div class="field">
    <%= f.label :hour, 'Time' %><br />
    <%= select_hour @meeting.hour || 12, {:ampm => true}, {:name => 'meeting[hour]', :id => 'meeting_hour'} %> : 
    <%= select_minute @meeting.minute || 0, {:minute_step => 5}, {:name => 'meeting[minute]', :id => 'meeting_minute'} %>
  </div>
  <div class="field">
    <%= f.label :topic %><br />
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
  loadGoogleMap(<%= @meeting.meeting_address.lat %>, <%= @meeting.meeting_address.lng %>);
  $('.new_address input').change(function(){refreshMap()});
  $('#link_new_address a').click(function(){$('.new_address').show(); $('.existing_address').remove(); return false; });
</script>

<%= link_to 'Back', admin_meetings_path %> | 
<%= link_to 'Remove this Meeting', admin_meeting_path(@meeting), :method => :delete, :confirm => "Are you sure?" %>

app/views/admin/meetings/index.html.erb
<h1>Meeting List</h1>

<% District.all.each do |district| %>
<table class="meeting_list" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th class="district" colspan="8"><h3><%= district.name %></h3></th>
    </tr>
    <tr>
      <th></th>
      <% Date::DAYNAMES.each do |day| %>
        <th><%= day[0..2].upcase %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% district.meeting_addresses.each do |meeting_address| %>
    <tr>
      <td class="building"><%= meeting_address.building %><br><div class="note"><%= meeting_address.street1 %> <%= meeting_address.street2 %></div></td>
      <% 7.times do |wday| %>
        <td class="time">
          <% meeting_address.meetings.each do |meeting| %>
            <% if wday == meeting.wday %>
              <%= link_to meeting.time, edit_admin_meeting_path(meeting) %>
              <% unless meeting.topic.blank? %>
                <br><span class="note">(<%= raw meeting.topic %>)</span>
              <% end %>
            <% end %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<%= link_to 'Add a Meeting', new_admin_meeting_path %>

app/views/admin/meetings/new.html.erb
<h1>New meeting</h1>

<%= form_for([:admin,@meeting]) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h1><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h1>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <fieldset class="existing_address">
    <%= f.select :meeting_address_id, option_groups_from_collection_for_select(District.all, :meeting_addresses, :name, :id, :short_address, 0), :include_blank => true %>
    <p id="link_new_address">or <%= link_to "create a new address", new_admin_meeting_address_path %></p>
  </fieldset>
  
  <fieldset class="new_address" style="display: none">
  <%= fields_for @meeting.meeting_address do |af| %>
    <%= af.hidden_field :lat, :id => 'google_maps_address_lat' %>
    <%= af.hidden_field :lng, :id => 'google_maps_address_lng' %>
  
    <div class="field">
      <%= af.label :district_id %><br />
      <%= af.select :district_id, District.all.collect{|d| [d.name, d.id]}.sort %>
    </div>

    <div class="field">
      <%= af.label :building %><br />
      <%= af.text_field :building %>
    </div>
    <div class="field">
      <%= af.label :street1 %><br />
      <%= af.text_field :street1 %>
    </div>
    <div class="field">
      <%= af.label :street2 %><br />
      <%= af.text_field :street2 %>
    </div>
    <div class="field">
      <%= af.label :city %><br />
      <%= af.text_field :city %>
    </div>
    <div class="field">
      <%= af.label :state %><br />
      <%= af.text_field :state, :class => "uppercase" %>
    </div>
    <div class="field">
      <%= af.label :zip_code %><br />
      <%= af.text_field :zip_code %>
    </div>
    <div class="field">
      <%= af.label :notes %><br />
      <%= af.text_field :notes %>
    </div>
  <% end %>

  <div id="google_map">
  </div>
  
  </fieldset>
  
  <div class="field">
    <%= f.label :wday, 'Day' %><br />
    <%= f.select :wday, Date::DAYNAMES.zip((0..6).to_a) %>
  </div>
  <div class="field">
    <%= f.label :hour, 'Time' %><br />
    <%= select_hour 12, {:ampm => true}, {:name => 'meeting[hour]', :id => 'meeting_hour'} %> : 
    <%= select_minute 0, {:minute_step => 5}, {:name => 'meeting[minute]', :id => 'meeting_minute'} %>
  </div>
  <div class="field">
    <%= f.label :topic %><br />
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
  loadGoogleMap();
  $('.new_address input').change(function(){refreshMap()});
  $('#link_new_address a').click(function(){$('.new_address').show(); $('.existing_address').remove(); return false; });
  // $('form input[type="submit"]').click(function(){refreshMap()});
</script>

<%= link_to 'Back', admin_meetings_path %>

app/views/admin/meetings/show.html.erb
<h1>Meeting Detail</h1>

<h3><%= @meeting.title %></h3>
<dl>
  <dt>Day of Week:</dt><dd><%= @meeting.day %></dd>
  <dt>Time of Day:</dt><dd><%= @meeting.time %></dd>
  <dt>Location:</dt>
  <dd class="clearfix">
    <address>
      <%= @meeting.meeting_address.building %><br>
      <%= @meeting.meeting_address.street1 %>
      <%= @meeting.meeting_address.street2 %><br>
      <%= @meeting.meeting_address.city %>, <%= @meeting.meeting_address.state %> <%= @meeting.meeting_address.zip_code %><br>
      <%= @meeting.meeting_address.notes %>
    </address>
  </dd>
  <% unless @meeting.topic.blank? %><dt>Meeting Focus:</dt><dd><%= @meeting.topic %></dd><% end %>
</dl>

<div id="google_map"></div>

<br>
<%= link_to 'Back to Meetings', admin_meetings_path %> | 
<%= link_to 'Remove this Meeting', admin_meeting_path(@meeting), :method => :delete, :confirm => "Are you sure?" %>


<script type="text/javascript" charset="utf-8">
  loadGoogleMap(<%= @meeting.meeting_address.lat %>, <%= @meeting.meeting_address.lng %>);
</script>