config/routes.rb
Coda::Application.routes.draw do

  match '/documents/:type'                => 'documents#index',     :as => :typed_documents, :constraints => {:type => /\D+/}
  match '/info/:slug'                     => 'pages#show',          :as => :view_page
  match '/intergroup'                     => 'pages#intergroup',    :as => :intergroup
  match '/contact'                        => 'messages#new',        :as => :contact
  
  match '/messages'                       => 'messages#new',              :via => :get
  match '/messages/voicemail'             => 'messages#create_voicemail', :via => :post

  match '/meetings/address/:address_id'   => 'meetings#index',      :as => :meetings_by_address
  match '/meetings/:district'             => 'meetings#index',      :as => :meetings_by_district, :constraints => {:district => /\D+/}
  
  match '/forums/:id/posts/new'           => 'forum_posts#new',     :as => :new_post_in_forum, :constraints => {:id => /\d+/}
  match '/forum_posts/:id/replies/new'    => 'forum_replies#new',   :as => :new_reply_to_post, :constraints => {:id => /\d+/}
  
  match 'announcements_ticker'            => 'announcements#index', :as => :announcements_ticker, :defaults => {:limit => 5, :format => 'json'}
  
  
  resources :announcements, :only => [:show, :index], :default => {:format => 'html'}
  resources :documents, :only => [:show, :index]
  resources :motions, :only => [:show, :index]
  resources :intergroup_sessions, :only => [:show, :index]
  resources :meetings, :only => [:show, :index]
  resources :transactions
  resources :messages, :only => [:new, :create, :show]
  resources :forums, :only => [:index, :show]
  resources :forum_posts
  resources :forum_replies, :only => [:create]

  match '/admin'                                  => 'admin/admin#admin',                  :as => :admin                                 
  match '/admin/documents/add_transaction'        => 'admin/documents#add_transaction',    :as => :add_admin_document_transaction
  match '/admin/documents/update_transaction/:id' => 'admin/documents#update_transaction', :as => :update_admin_document_transaction
  match '/admin/messages/:id/status/:status'      => 'admin/messages#status',              :as => :update_admin_message_status
  match '/admin/messages/all'                     => 'admin/messages#index',               :as => :admin_all_messages, :defaults => { :show_all => 'true' }
  
  namespace :admin do
    resources :announcements
    resources :contents
    resources :pages
    resources :documents
    resources :motions
    resources :intergroup_sessions
    resources :districts
    resources :meetings
    resources :meeting_addresses
    resources :menus
    resources :messages
    resources :transactions
    resources :site_configs
    resources :forums
  end
  

  match '/twilio/start'                                                  => 'twilio#start', :defaults => { :format => 'xml' }
  match '/twilio/district_list'                                          => 'twilio#district_list', :defaults => { :format => 'xml' }
  match '/twilio/meeting_list/:district_id'                              => 'twilio#meeting_list', :defaults => { :format => 'xml' }
  match '/twilio/meeting_list/:district_id/meeting_detail/:meeting_id'   => 'twilio#meeting_detail', :defaults => { :format => 'xml' }
  match '/twilio/info/:key'                                              => 'twilio#info', :defaults => { :format => 'xml' }
  match '/twilio/voicemail'                                              => 'twilio#voicemail', :defaults => { :format => 'xml' }
  

  root :to => 'pages#home'

end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < ApplicationController
  http_basic_authenticate_with :name => SITE_CONFIG['username'], :password => SITE_CONFIG['password'] if SITE_CONFIG['perform_authentication']
  layout 'admin'

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new
    @other_documents = {'Other' => Document.where("intergroup_session_id is null and id > 1").collect{|d| [d.title, d.id]} }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
    @other_documents = {'Other' => Document.where("intergroup_session_id is null and id > 1").collect{|d| [d.title, d.id]} }
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to admin_transaction_path(@transaction), notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to admin_transaction_path(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/transactions/_form.html.erb
<%= form_for([:admin,@transaction]) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h1><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h1>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :document_id %><br />
    <%= f.select :document_id, option_groups_from_collection_for_select(IntergroupSession.all, :documents, :name, :id, :title, @transaction.document_id) + grouped_options_for_select(@other_documents, @transaction.document_id), :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :method %><br />
    <%= f.select :method, Transaction::METHODS %>
  </div>
  <div class="field">
    <%= f.label :expense, "Type" %><br />
    <%= f.select :expense, [["Income",0], ["Expense", 1]], :selected => @transaction.expense  ? 1 : 0 %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br />
    <%= f.date_select :timestamp, :order => [:month, :day, :year] %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_transaction_path(@transaction) %> |
<%= link_to 'Back', admin_transactions_path %>

app/views/admin/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Document</th>
    <th>Amount</th>
    <th>Method</th>
    <th>Timestamp</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= link_to transaction.document.title, admin_document_path(transaction.document) unless transaction.document.nil? %></td>
    <td class="<%= 'expense' if transaction.expense? %>"><%= number_to_currency transaction.pretty_amount %></td>
    <td><%= transaction.pretty_method %></td>
    <td><%= nice_date transaction.timestamp %></td>
    <td><%= transaction.description %></td>
    <td><%= link_to 'Show', admin_transaction_path(transaction) %></td>
    <td><%= link_to 'Edit', edit_admin_transaction_path(transaction) %></td>
    <td><%= link_to 'Remove', admin_transaction_path(transaction), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_admin_transaction_path %>

app/views/admin/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_transactions_path %>

app/views/admin/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<% unless @transaction.document.nil? %>
<p>
  <b>Document:</b>
  <%= @transaction.document.title %>
</p>
<% end %>

<p>
  <b>Amount:</b>
  <%= number_to_currency(@transaction.pretty_amount)%>
</p>

<p>
  <b>Method:</b>
  <%= @transaction.pretty_method %>
</p>

<p>
  <b>Timestamp:</b>
  <%= nice_date @transaction.timestamp %>
</p>

<p>
  <b>Description:</b>
  <%= @transaction.description %>
</p>


<%= link_to 'Edit', edit_admin_transaction_path(@transaction) %> |
<%= link_to 'Back', admin_transactions_path %>